### PR TITLE
get the anatomy guide started

### PR DESCRIPTION
**Pull request by connor11528**
Here is the basic structure. We can for sure dig deeper here but something is better than nothing!

### CODE REVIEW

**Comment by connor11528** [comment]
Also could add these notes from @jaumard 

http://blog.jaumard.com/en/2016/01/05/getting-started-with-trails/

```
env : Config file that overrides the default per environment, you can change the entire config for your production environment
database : Information about your database: type, migration strategy, et cetera.
footprints : Options for your REST API: add a prefix, enable/disable footprint, et cetera.
i18n : Configuration for multi language support: set default language and translations.
locales : Folder in which to put all translation files
log : Logger options for your project. Uses winston by default.
main : Allow you to enable/disable trailpacks.*
policies : Allow you to map your policies with controllers.
routes : Allows you to map your controller’s functions with routes.
session : Options for managing sessions: strategies, cookies, web tokens, et cetera.
views : Allow you to configure your template engine.
web : Options for web server, like port.
webpack : Configuration for building assets, it’s a default webpack configuration (http://webpack.github.io/docs/configuration.html)
```

**Comment by maissani** [comment]
@connor11528 , i agree with your point of view.

**Comment by maissani** [comment]
Can you add an ExampleModel.js, examplepolicy in the list :) 
:file_folder:

**Comment by connor11528** [comment]
Okay added in notes. Is that closer? Added exampleModel and examplePolicy

**Comment by maissani** [comment]
Why did you add notes ? Theses info shouldn't be there , this is my opinion.
Don't warp your directory tree because i couldn't implement direct link to anatomy files with []() when warped between codeblock.

**Comment by maissani** [comment]
Models and Policies that all and i ll accept the PR :+1: Then i will implement links

**Comment by maissani** [comment]
Your information is usefull but i think this should be under respective directories.

**Comment by connor11528** [comment]
Okay I'm a trails n00b and don't know exactly how models and policies work. Deleted the notes

**Comment by maissani** [comment]
Your are not a noob , there is no noob there, there is just code lovers. 
Your Notes has to been under config folder of trails Anatomy. 
The list that you provide is just a simple Sumary that contains links forwarding to docs and files respectively.

**Comment by maissani** [comment]
@connor11528 If you can continue , you will be welcome. :) I made some change with your declaration to get everything more prety and more readable. I also give an example of linking ( api ) .

**Comment by connor11528** [comment]
awesome great news. We can build out this documentation for sure! It's an asset for the community

have a great day

**Pull request merged**
