### PR TITLE
Update policy.md

### PR DESCRIPTION
**Pull request by clayrisser**
Isn't this the correct way to implement a policy? The way it's documented did not work for me, but this worked.

https://github.com/trailsjs/trails/issues/300

### CODE REVIEW

**Comment by jaumard** [comment]
In fact doc is done for hapi mainly :( and with hapi the previous one was working (and the one you use should also work with hapi) maybe trailpack-express should be modified to allow same as hapi...

@trailsjs/maintainers any feedback here ?

**Comment by clayrisser** [comment]
Ah, that explains things. We should schedule a time for you to go over in detail the inner workings of the express-trailpack

**Comment by clayrisser** [comment]
I use it heavily enough that I don't mind (actually want to ) help maintain it.

**Comment by clayrisser** [comment]
I love Trails, but I like to use it like Sails.

**Comment by clayrisser** [comment]
Oh, btw, maybe this way of adding policies should still be added to the documentation.

**Comment by clayrisser** [comment]
https://github.com/trailsjs/doc/pull/41

**Comment by jaumard** [comment]
Definitely need to be on documentation if hapi supports it, or have clear separation on hapi/express doc and support as we will have some differences between the two...

Don't hesitate to ping me on gitter if you have trouble with trailpack-express or don't understand internal stuff on it :)

**Comment by scott-wyatt** [comment]
This reminds me, I have a PR to submit for either express or trailpack-router.

**Comment by clayrisser** [comment]
Cool thanks. I'm going to close this, but I created a new pull request with the alternative way of adding a policy.

**Pull request closed without merging**
