### PR TITLE
Added Docker documentation

### PR DESCRIPTION
**Pull request by clayrisser**

### CODE REVIEW

**Comment by scott-wyatt** [comment]
Great work! I might recommend adding a short blurb at the top describing what docker is and a link to the download page for the beginners.

**Comment by clayrisser** [comment]
Ok, sure

**Comment by scott-wyatt** [comment]
@jaumard This looks good to me.

**Comment by jaumard** [comment]
For me too :) thanks @jamrizzi ! It will help a lot I think :)

**Pull request merged**
